sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libncurses5-dev
language: bash

before_script:
  - ulimit -c unlimited -S
  
script:
  - set |grep =|grep '@'
  - ./build.sh
  - ./upload.sh
